language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/pet/pet-client/node_modules"
  - "$HOME/pet/pet-client/bower_components"
before_install:
- npm install -g npm@^3
- npm install -g bower
node_js: '6'
install:
- mvn clean install
script:
- cd pet-client
- npm install
- bower install
- npm test
- cd ../pet-server
deploy:
  edge: true
  provider: cloudfoundry
  username: Ray.Gill
  password:
    secure: KlG+QVNFB3izjnUKbXiaAh+DlACiPlo43iQusUq7mSZDFsg3p3+peW3u4oyq4Jne00nVO5XbWFBGoCR4aQFKRSd86A/qe0UwdLnWgNX+kxviEFH9tLfTSCzSXfZylZ4MaWjJCp5dPiEGoq8Zhn7hLoNiSIKdeVl2M1vfvSIpNOEhsGXYT/6+J65SQmXdpKpOR3GFaVoPUHJng8J8DfTkwIH4QChCsTH6fyFP1OHGC3vsqr3hiioYY/K9i1O3wxxn/DSGU7K/B59VdEqO8zdFRvI7XN44pgUciTQJKLwi+qBPOUJE5b6A56qsf2MikqtcB92xMxPEpWbgtOWTs83oC8aBDL7Kjwl7g4+xPncXWe6xNYzf9H4FBiYXmH4SmiyAWMyeqqsoEZRzKw39o2AkhpzJHGOXgd6GFm/ti0zjnvGAp0HFZcyANsbyDn8IAx/7LrLE5tDaA/XQr7sgSnAWSpj8rQUqixaWlAtYy6o5lL7fi5yQPhocdxh004f8ue/rQlnUrJDGzhXJNbMdmjLbZ+JZmJedYN1uPGavPzf5xdkXKdReW1J9Ep/ZdDFdWxMIKq4+tEdqkpVxbwUPevc7mficiiYbH9YLoDQye3pYTiQ4OtCcW8zeO2d7Jy5je/CTNTxD3yiVypXyMp6h4odymhb1FH5F4GI6EuL1EjKn+Sk=
  api: "--skip-ssl-validation https://api.pcf-system.intware.com"
  organization: XtremeLearning
  space: travis-dev
